import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Lato } from 'next/font/google'
import './globals.css';
import CartProvider from './components/Providers';
import Navbar from './components/Navbar';
import ShoppingCartModal from './components/ShoppingCartModal';

const lato = Lato({
  weight: '400',
  subsets: ['latin'],
})

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
})
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className={lato.className}>
				<CartProvider>
					<div className={inter.className}>
						<Navbar />
					</div>
					<ShoppingCartModal />
					{children}
				</CartProvider>
			</body>
		</html>
	);
}
